import { dom } from './dom'
import { error } from './error'
import { fetch } from './fetch'
import { hash } from './hash'
import { history } from './history'
import { perf } from './performance'
import { reject } from './reject'
import { vue } from './vue'
import { xhr } from './xhr'
export const defaultPlugins = [vue(), xhr(), perf(), history(), hash(), fetch(), dom(), reject(), error()]
export * from './dom'
export * from './error'
export * from './fetch'
export * from './hash'
export * from './history'
export * from './micro'
export * from './performance'
export * from './reject'
export * from './xhr'
export * from './vue'
export * from './rrweb'
