version: "3.7"

services:
  app:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - mongo  
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data
    ports:
      - '27017:27017'

volumes:
  mongo:
 

