version: "3.7"

services:
  app:
    build: 
      context: ./
      dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - mongo  
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongodb_data:
 

