version: '3.7'

networks:
    demo-net:
        name: demo-net
        driver: bridge

volumes:
    db:

services:
    mizar-server:
        container_name: mizar-server
        image: mizar-server
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        networks:
            - demo-net
        ports:
            - 3000:3000
        depends_on:
            - db

    db:
        image: mongo:5.0.1
        restart: always
        volumes:
            - db:/data/db
        networks:
            - demo-net
        ports:
            - 27017:27017    

    