version: "3.8"
services:
    api:
        # image: thomas-oliver/nestjs-dockerized 
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - mongo
        environment: 
            DATABASE_URL: postgres://user:password@postgres:5432/db
            NODE_ENV: development
            PORT: 3000
        ports:
            - "3000:3000"

    mongo:
        image: mongo:5.0
        ports:
            - "27017:27017"

