/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./src/components/a.vue')['default']
    ABadge: typeof import('@arco-design/web-vue')['Badge']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACollapse: typeof import('@arco-design/web-vue')['Collapse']
    ACollapseItem: typeof import('@arco-design/web-vue')['CollapseItem']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    ARangePicker: typeof import('@arco-design/web-vue')['RangePicker']
    AScrollbar: typeof import('@arco-design/web-vue')['Scrollbar']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATimeline: typeof import('@arco-design/web-vue')['Timeline']
    ATimelineItem: typeof import('@arco-design/web-vue')['TimelineItem']
    AutoImport: typeof import('./src/components/AutoImport.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    ErrorActions: typeof import('./src/views/ErrorActions.vue')['default']
    ErrorInstance: typeof import('./src/views/ErrorInstance.vue')['default']
    ErrorPlayback: typeof import('./src/views/ErrorPlayback.vue')['default']
    ErrorRecord: typeof import('./src/views/ErrorRecord.vue')['default']
    ErrorStatistics: typeof import('./src/views/ErrorStatistics.vue')['default']
    FixCard: typeof import('./src/components/FixCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    'ILucide:arrowDown': typeof import('~icons/lucide/arrow-down')['default']
    'ILucide:play': typeof import('~icons/lucide/play')['default']
    'ILucide:refreshCw': typeof import('~icons/lucide/refresh-cw')['default']
    'ILucide:triangle': typeof import('~icons/lucide/triangle')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
